---
services:
  kali:
    build:
      context: .
      dockerfile: kali.Dockerfile
      shm_size: "512m"
    ports:
      - "6901:6901"
    environment:
      VNC_PW: "password"
    cap_add:
      - NET_ADMIN
      - NET_RAW

  cowrie:
    image: cowrie/cowrie
    ports:
      - "2222:2222"

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
